apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgCelupXVfxxb4um+u6GByiJkQRCDxStGlxK4btaXtQ5pFG0fiCChi+YuBfadyImAWfZYCVp8/VUksF4KjIfP6uXz7FKp2Hi2cO5QJ7maPS3gjAMUnpgia+Sm0uZ5aA7zeUvzQmT6Z6wTREEBYMEYedIyVYzvF1REJZ4pLyjZd68VmYAQYIRZ40KR3I738WvE5JJm+nJC1ZOyHuewRro83XyX9k0LO/maRX3qfYwxr7lWK0Mc+BJY0ssCEquCf/TZQsIkEZqM8SeLqBj/XdfLvLxsviLYakw7WYu9MEFsLVnuo66BocXiRvbgn0HmTE9CgnRpU2JlA69OqmpVe/ae7qglvzlSumF+QbLd+4JqSvzpAmgGqrkhbOGsM09uAeuC1BLjVc1RYOdFsQETE8v88Zx+9X6iXWB4fjrg+U6Q+uWWC2esTmVtnxdckcewvaBMc0LyUN1SZDvk7muoQid1GRCE1SPF3jrM+emMNtTOSLvHobsIolKzTB9LmJ1laAmNqDYlQ9xWsi5zTwB9DCwRhvM7eM17DtR6AzPGLYvoFMbuuGhh1ZcLLLePyCbtkr/cFa7b+/Apz0ZWinfCaLM6EffYucSe1kOZokZ3F1D+E1scCSIUQg1K1i5EpuP6usMaTaROUhfBFKS4hfAPzmJ6NE9BJwlJez8P4olSv2nV4X5SthetcWf3bsrcvaRSE4iOKvd8Du6jOK5cT8RrBxbnQpjwckDvk+yrUjhV6ybHce6rlTx1jKPKlpy
    username: AgBPfSwqNQBQduQhTuVdwfS8C4+WLXmkRM6qQG/L2fA/vm4a0+OTfNr+ubX3btD+DqPYeG348uEy/IPcmGukLMyKlwAA/peKFCkTzHQyzhiENxsEjqtoRmpQ4cnSq6lLYv9N/uAw3O585YwhWs/3h0lIPYwxJdPCHfbtXRvmSxgAdi56/w9frjFccwwH12Cs6otxZ+/dQUcGzORF1rsp7OPzQ+GPVqUhd6OgHE/98LmQtIqoFqNNP+ebKYhUUfhCOK9t3gmMVujjVspbdevGyLD/9SSOpodxxLshFtnGOMg6HbNBSYrdBjbRQq5sMUqduaTW2DGzrMrm0jpzQDQRZXjxwm0ilQGlHX9OJzxq4cMiCJuXsayFlICrkE+GWb2Hs0/H3Vasd5MTY7hB2PXRBv0hFOyuUEGhg6gjK6L8qQyhtFtR3B7Tz0HWdspVMuJ/eBtCYLgYAFk6wnSC+Ikh2v0AU8sxkmS49JZqkmMY+0T8ImKHpYdRnspMKZTeIzTqhL05LTmgm4of/QPM62zwToULDwvqdI3JTPjDYT3SlKKE7gGv59zG8cTKTgUagmZ7//r0DBX0B/HuXoFwVw/lV+wf2kz6lZz1guLUZbl9dDYjB+3+uR1tcuUNBNl1gnLfn8V0dR9iMS/0x7adurFlq3nPlUId7rlv5Me05g4vDKjwUWa8KwIlsDyig8iBtxCkbPAG10u5cRmc
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

